# -*- coding: utf-8 -*-
"""DEVLET-500-1000 — 500-1000 kusagi kunyeleri (UYGULA betigi verisi).

Kaynak: denetim/DEVLET-500-1000-KUNYE.json (DEVLET-500-1000 oturumu).
🔴 O oturum teslimini M-5682'de yapti; KUNYE-1945-0930 son birlestirmesini
   M-5603'te yapmisti ⇒ bu kusagin kunyeleri HIC BIRLESTIRILMEDI.
   Sonuc olculdu: data/kronoloji_cok_500_1000.js'in 16 maddesinden 7'si
   BAGSIZ kaldi (12 kimlik eslenmiyordu: hulefa-yi-rasidin 4 · aglebi 2 ·
   tolunogullari 2 · hamdani-musul 2 · sasani · hazar-kaganligi · emevi ·
   rustemi · ziyadi · saffari · ihsidi · midrari).
"""

BANNER = ("DEVLET-500-1000 (1 Ekim 2026): 500-1000 kusagi kunyeleri — kronoloji_cok_500_1000.js'in taraflari")

UZAT = []

YENI = [
    {"id": "hulefa-yi-rasidin", "ad": "Hulefâ-yi Râşidîn Devri (Medine Hilâfeti)", "tur": "devlet", "bolge": "arabistan",
     "f": "0632-01-01", "t": "0661-01-01", "baskent": "Medine → Kûfe",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı: 'Hz. Peygamber’den sonraki ilk dört halife (632-661)' — YIL. Gün yazılmadı; başlangıç Ebû Bekir'e biat.",
     "ic_not_t": "TDV emeviler: 'Hz. Hasan’ın … kendisine biat etmesiyle 41 yılı Rebîülevvel ayının sonlarında (Temmuz 661)' — AY biliniyor, gün yok ⇒ YYYY-01-01 (ay yazılmaz, CLAUDE.md §8).",
     "ozet": "Hz. Peygamber'in vefatından sonra Hz. Ebû Bekir, Ömer, Osman ve Ali'nin hilâfetleriyle süren ilk dört halife devri; Hz. Hasan'ın Muâviye'ye biatıyla sona erdi. (kaynak: TDV, madde: hulefa-yi-rasidin)",
     "kaynak": "TDV: hulefa-yi-rasidin (HULEFÂ-yi RÂŞİDÎN)",
     "kron": [
         ("0632-01-01", "kurulus", "Hz. Peygamber'in vefatının ardından Hz. Ebû Bekir'e biat edildi", "TDV hulefa-yi-rasidin (yıl)"),
         ("0661-01-01", "son", "Hz. Ali şehit edildi; Hz. Hasan'ın Muâviye'ye biatıyla Râşid halifeler devri sona erdi (Temmuz 661)", "TDV emeviler: '41 yılı Rebîülevvel ayının sonlarında (Temmuz 661)'"),
     ]},
    {"id": "emevi", "ad": "Emevî Hilâfeti (Benî Ümeyye)", "tur": "devlet", "bolge": "suriye-filistin",
     "f": "0661-01-01", "t": "0750-08-05", "baskent": "Dımaşk",
     "boya_gerekli": True,
     "ic_not_f": "TDV: '41 yılı Rebîülevvel ayının sonlarında (Temmuz 661) İslâm dünyasının tamamını hâkimiyeti altına aldı' — AY; gün yok ⇒ 0661-01-01.",
     "ic_not_t": "TDV: 'Mervân en sonunda Mısır’da öldürüldü (26 Zilhicce 132 / 5 Ağustos 750). Onun ölümüyle Emevîler tar…' — GÜN kaynaktan. abbasi künyesi 0749-11-28'de başlıyor; 9 aylık örtüşme iç savaş dönemidir (beyan). Endülüs Emevîleri ayrı künye (endulus-emevi, 756).",
     "ozet": "Muâviye b. Ebû Süfyân'ın kurduğu, Dımaşk merkezli ilk İslâm hânedan-devleti; Abbâsî ihtilâliyle yıkıldı, son halife II. Mervân Mısır'da öldürüldü. (kaynak: TDV, madde: emeviler)",
     "kaynak": "TDV: emeviler (EMEVÎLER)",
     "kron": [
         ("0661-01-01", "kurulus", "Hz. Hasan'ın biatıyla Muâviye bütün İslâm dünyasına hâkim oldu; Emevî Devleti kuruldu (Temmuz 661)", "TDV emeviler: '(Temmuz 661)'"),
         ("0750-08-05", "son", "Zap yenilgisinden sonra kaçan II. Mervân Mısır'da öldürüldü; Emevî Hilâfeti sona erdi", "TDV emeviler: '(26 Zilhicce 132 / 5 Ağustos 750)'"),
     ]},
    {"id": "sasani", "ad": "Sâsânî İmparatorluğu", "tur": "imparatorluk", "bolge": "iran",
     "f": "0226-01-01", "t": "0651-01-01", "baskent": "Medâin (Ktesifon)",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı: '226-651 yılları arasında hüküm süren bir İran hânedanı' — YIL. Kuşak 500'de başlar; f kuşak dışı ama künyenin gerçek başlangıcıdır (kırpılmadı).",
     "ic_not_t": "TDV: '651 yılında düşmanları tarafından Merv’de öldürülen Yezdicerd' — YIL.",
     "ozet": "Erdeşîr-i Bâbekân'ın kurduğu İran hânedanı; Kādisiye ve Nihâvend yenilgilerinden sonra III. Yezdicerd'in Merv'de öldürülmesiyle sona erdi. (kaynak: TDV, madde: sasaniler)",
     "kaynak": "TDV: sasaniler (SÂSÂNÎLER)",
     "kron": [
         ("0226-01-01", "kurulus", "Erdeşîr-i Bâbekân Sâsânî hânedanını kurdu", "TDV sasaniler başlığı: '226-651' (yıl)"),
         ("0651-01-01", "son", "Son Sâsânî hükümdarı III. Yezdicerd Merv'de öldürüldü; imparatorluk sona erdi", "TDV sasaniler (yıl)"),
     ]},
    {"id": "tahiri-horasan", "ad": "Tâhirîler (Horasan)", "tur": "hanedanlik", "bolge": "iran",
     "f": "0821-01-01", "t": "0873-01-01", "baskent": "Merv → Nîşâbur",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı: 'Horasan ve Mâverâünnehir’de hüküm süren bir hânedan (821-873)' — YIL. 'tahiriler' slug'ı 302 (ölü); canlı madde 'tahiriler--horasan'. 'tahiri' id'si Yemen Tâhirîleri'ne (1454) ait — karıştırma.",
     "ic_not_t": "TDV: 'Ya‘kūb b. Leys, Şevval 259 (Ağustos 873) tarihinde Nîşâbur’u da alarak Tâhirîler’in Horasan’daki hâkimiyetine son verdi' — AY; gün yok ⇒ 0873-01-01.",
     "ozet": "Tâhir b. Hüseyin'in Abbâsî valisi olarak Horasan'da kurduğu yarı bağımsız hânedan; Ya'kūb b. Leys Nîşâbur'u alınca sona erdi. (kaynak: TDV, madde: tahiriler--horasan)",
     "kaynak": "TDV: tahiriler--horasan (TÂHİRÎLER)",
     "kron": [
         ("0821-01-01", "kurulus", "Tâhir b. Hüseyin Horasan valiliğine tayin edildi; Tâhirî hânedanı başladı", "TDV tahiriler--horasan (yıl)"),
         ("0844-01-01", "hukumdar", "Abdullah b. Tâhir öldü; yerine oğlu II. Tâhir geçti", "TDV tahiriler--horasan: '(230/844)'"),
         ("0873-01-01", "son", "Saffârî Ya'kūb b. Leys Nîşâbur'u aldı; Tâhirîler'in Horasan hâkimiyeti sona erdi (Ağustos 873)", "TDV tahiriler--horasan: 'Şevval 259 (Ağustos 873)'"),
     ]},
    {"id": "saffari", "ad": "Saffârîler", "tur": "hanedanlik", "bolge": "iran",
     "f": "0861-01-01", "t": "1003-01-01", "baskent": "Zerenc",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'Ya‘kūb b. Leys es-Saffâr, 247’de (861) Sîstan’a hâkim olduktan sonra' — YIL.",
     "ic_not_t": "TDV: 'Sultan Mahmud onu ele geçirdi … Böylece Saffârîler hânedanı sona erdi (393/1003)' — YIL. t kuşak dışı (1003); gerçek son, kırpılmadı. Ara kesinti: Leysîler kolu 'Receb 298 / Mart 911' Sâmânîler'e düştü.",
     "ozet": "Ya'kūb b. Leys es-Saffâr'ın Sîstan'da kurduğu hânedan; Horasan'dan Fars'a yayıldı, Sâmânîler'e ve sonunda Gazneli Mahmud'a yenilerek sona erdi. (kaynak: TDV, madde: saffariler)",
     "kaynak": "TDV: saffariler (SAFFÂRÎLER)",
     "kron": [
         ("0861-01-01", "kurulus", "Ya'kūb b. Leys Sîstan'a hâkim oldu; Saffârî hânedanı kuruldu", "TDV saffariler: '247’de (861)'"),
         ("0879-06-09", "hukumdar", "Ya'kūb b. Leys öldü; yerine kardeşi Amr b. Leys geçti", "TDV saffariler: '(14 Şevval 265 / 9 Haziran 879)'"),
         ("1003-01-01", "son", "Gazneli Mahmud Sîstan'ı alıp Halef'i ele geçirdi; Saffârîler sona erdi", "TDV saffariler: '(393/1003)'"),
     ]},
    {"id": "sacogullari", "ad": "Sâcoğulları (Azerbaycan)", "tur": "hanedanlik", "bolge": "kafkasya",
     "f": "0889-01-01", "t": "0929-01-01", "baskent": "Merâga → Erdebîl",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı: 'Azerbaycan’da hüküm süren bir Türk-İslâm hânedanı (889-929)' — YIL. bolge 'kafkasya' mı 'iran' mı: merkez Merâga (İran Azerbaycanı) — koordinatör seçsin.",
     "ic_not_t": "TDV başlığı (929) — YIL; gövdede son cümle ayrıca ölçülmedi.",
     "ozet": "Üsrûşene kökenli Ebü's-Sâc ailesinin Abbâsî valisi sıfatıyla Azerbaycan ve Ermenistan'da kurduğu Türk-İslâm hânedanı. (kaynak: TDV, madde: sacogullari)",
     "kaynak": "TDV: sacogullari (SÂCOĞULLARI)",
     "kron": [
         ("0889-01-01", "kurulus", "Muhammed b. Ebü's-Sâc Azerbaycan valisi oldu; Sâcoğulları hânedanı başladı", "TDV sacogullari (yıl)"),
         ("0893-01-01", "baskent", "Muhammed b. Ebü's-Sâc Merâga'yı alıp idare merkezi yaptı", "TDV sacogullari: '(280/893)'"),
         ("0929-01-01", "son", "Sâcoğulları hânedanı sona erdi", "TDV sacogullari başlığı (yıl)"),
     ]},
    {"id": "tolunogullari", "ad": "Tolunoğulları", "tur": "hanedanlik", "bolge": "misir-sudan",
     "f": "0868-01-01", "t": "0905-01-01", "baskent": "Fustat → Katâi",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'Mısır Valisi Bayık Bey’in vekili sıfatıyla Mısır’a girdi, bu vesileyle hânedanın temellerini attı (254/868)' — YIL. 'tulunogullari' slug'ı 302.",
     "ic_not_t": "TDV: 'Şeybân … teslim oldu (Rebîülevvel 292 / Ocak 905). Ertesi gün Abbâsî ordusu Fustat’a girdi' — AY; gün yok ⇒ 0905-01-01 (tesadüfen Ocak; ay hassasiyeti ic_not'ta).",
     "ozet": "Ahmed b. Tolun'un Mısır'da kurduğu, İslâm döneminde Mısır'ın ilk müstakil hânedanı; Suriye'ye yayıldı, Abbâsî ordusu Fustat'a girince yıkıldı. (kaynak: TDV, madde: tolunogullari)",
     "kaynak": "TDV: tolunogullari (TOLUNOĞULLARI)",
     "kron": [
         ("0868-01-01", "kurulus", "Ahmed b. Tolun vali vekili olarak Mısır'a girdi; Tolunoğulları'nın temelleri atıldı", "TDV tolunogullari: '(254/868)'"),
         ("0893-06-14", "toprak-kazanc", "Halife Mu'tazıd'ın fermanıyla Fırat'tan Berka'ya kadar topraklar Humâreveyh'e verildi", "TDV tolunogullari: '14 Haziran 893’te Mısır’a yolladığı fermanla'"),
         ("0905-01-01", "son", "Şeybân b. Ahmed teslim oldu, Abbâsî ordusu Fustat'a girdi; Tolunoğulları yıkıldı (Ocak 905)", "TDV tolunogullari: '(Rebîülevvel 292 / Ocak 905)'"),
     ]},
    {"id": "ihsidi", "ad": "İhşîdîler", "tur": "hanedanlik", "bolge": "misir-sudan",
     "f": "0935-01-01", "t": "0969-07-06", "baskent": "Fustat",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'Mısır’da İhşîdîler döneminin temelleri atılmış oldu (Ramazan 323 / Ağustos 935)' — AY ⇒ 0935-01-01.",
     "ic_not_t": "TDV: '(17 Şâban 358 / 6 Temmuz 969). Cevher aynı gün Fustat’a girdi. Böylece İhşîdîler Devleti sona erdi.' — GÜN kaynaktan. fatimi künyesinin Mısır'a geçişiyle aynı gün.",
     "ozet": "Fergana kökenli Muhammed b. Tuğç el-İhşîd'in Mısır, Suriye ve Filistin'de kurduğu Türk hânedanı; Fâtımî kumandanı Cevher Fustat'a girince sona erdi. (kaynak: TDV, madde: ihsidiler)",
     "kaynak": "TDV: ihsidiler (İHŞÎDÎLER)",
     "kron": [
         ("0935-01-01", "kurulus", "Muhammed b. Tuğç yeniden Mısır valiliğine atandı; İhşîdî dönemi başladı (Ağustos 935)", "TDV ihsidiler: '(Ramazan 323 / Ağustos 935)'"),
         ("0969-07-06", "son", "İhşîdî ileri gelenleri Cevher es-Sıkıllî'ye bağlılık bildirdi, Cevher Fustat'a girdi; İhşîdîler sona erdi", "TDV ihsidiler: '(17 Şâban 358 / 6 Temmuz 969)'"),
     ]},
    {"id": "aglebi", "ad": "Ağlebîler", "tur": "hanedanlik", "bolge": "kuzey-afrika",
     "f": "0800-01-01", "t": "0909-03-18", "baskent": "Kayrevan → Rakkāde",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı ve emîr listesi: '1. İbrâhim b. Ağleb 184 (800)' — YIL.",
     "ic_not_t": "TDV: 'Ziyâdetullah … 18 Mart 909’da götürebileceği kadar eşyayı yanına alarak Mısır’a kaçtı' — GÜN kaynaktan (son emîrin kaçışı; Fâtımîler 'başşehre giren' — giriş günü ayrı verilmemiş). fatimi künyesi 0909-01-01 (yıl) — tutarlı.",
     "ozet": "İbrâhim b. Ağleb'in Abbâsî valisi olarak İfrîkıye'de kurduğu hânedan; Sicilya'yı fethetti, Fâtımî dâîsi Ebû Abdullah eş-Şiî karşısında yıkıldı. (kaynak: TDV, madde: aglebiler)",
     "kaynak": "TDV: aglebiler (AĞLEBÎLER)",
     "kron": [
         ("0800-01-01", "kurulus", "İbrâhim b. Ağleb İfrîkıye valiliğine getirildi; Ağlebî hânedanı kuruldu", "TDV aglebiler: '184 (800)'"),
         ("0909-03-18", "son", "Son Ağlebî emîri III. Ziyâdetullah Fâtımîler önünden Mısır'a kaçtı; Ağlebî devleti sona erdi", "TDV aglebiler: '18 Mart 909’da'"),
     ]},
    {"id": "idrisi", "ad": "İdrîsîler", "tur": "hanedanlik", "bolge": "kuzey-afrika",
     "f": "0789-01-01", "t": "0985-01-01", "baskent": "Velîlâ → Fas → Hacerünnesr",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'Velîlâ merkez olmak üzere İdrîsîler’in temelleri atılmıştı (172/789)' — YIL.",
     "ic_not_t": "TDV: 'Hâcib İbn Ebû Âmir el-Mansûr tarafından gönderilen adamlar tarafından öldürüldü (375/985). II. Hasan’ın ölümüyle Mağrib-i Aksâ’da hüküm süren İdrîsî hânedanı sona ermiş oldu' — YIL. Ara kesinti: Mesâle b. Habbûs Fas'ı alıp İdrîsî yönetimine son verdi, Haccâm geri aldı (künye kesintisiz tutuldu).",
     "ozet": "Hz. Hasan soyundan I. İdrîs'in Berberî Evrebe kabilesinin desteğiyle Fas'ta kurduğu ilk İslâm hânedanı; Fâtımî ve Endülüs Emevî baskısı arasında sona erdi. (kaynak: TDV, madde: idrisiler)",
     "kaynak": "TDV: idrisiler (İDRÎSÎLER)",
     "kron": [
         ("0789-01-01", "kurulus", "I. İdrîs'e Velîlâ'da Evrebe kabilesince biat edildi; İdrîsî devleti kuruldu", "TDV idrisiler: '(172/789)'"),
         ("0985-01-01", "son", "Son İdrîsî II. Hasan, Hâcib el-Mansûr'un adamlarınca öldürüldü; hânedan sona erdi", "TDV idrisiler: '(375/985)'"),
     ]},
    {"id": "rustemi", "ad": "Rüstemîler", "tur": "hanedanlik", "bolge": "kuzey-afrika",
     "f": "0777-01-01", "t": "0909-01-01", "baskent": "Tâhert",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'imam seçildi ve Rüstemîler Devleti’ni resmen kurmuş oldu (160/777)' — YIL.",
     "ic_not_t": "TDV: 'Rüstemî hânedanını sona erdirdi (Şevval 296 / Temmuz 909)' — AY ⇒ 0909-01-01.",
     "ozet": "Abdurrahman b. Rüstem'in İbâzî-Berberî kabilelerin imamı seçilmesiyle Tâhert merkezli kurulan İbâzî imamet devleti; Fâtımî dâîsi Ebû Abdullah eş-Şiî Tâhert'i alınca sona erdi. (kaynak: TDV, madde: rustemiler)",
     "kaynak": "TDV: rustemiler (RÜSTEMÎLER)",
     "kron": [
         ("0777-01-01", "kurulus", "Abdurrahman b. Rüstem İbâzî imamı seçildi; Rüstemî devleti kuruldu, Tâhert merkez oldu", "TDV rustemiler: '(160/777)'"),
         ("0909-01-01", "son", "Fâtımî kumandanı Ebû Abdullah eş-Şiî Tâhert'e girdi; Rüstemî hânedanı sona erdi (Temmuz 909)", "TDV rustemiler: '(Şevval 296 / Temmuz 909)'"),
     ]},
    {"id": "midrari", "ad": "Midrârîler (Sicilmâse)", "tur": "hanedanlik", "bolge": "kuzey-afrika",
     "f": "0772-01-01", "t": "0976-01-01", "baskent": "Sicilmâse",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı '772-976'; gövde: 'Ebü’l-Kāsım idareyi tekrar kendisi üstlendi (155/772). Midrârîler bu tarihten 976 yılına kadar Sicilmâse’ye hâkim olmayı başardılar' — YIL. (Sicilmâse'nin kuruluşu 140/757 civarı; TDV hânedanı 772'den sayıyor.)",
     "ic_not_t": "TDV: 'Hazrûn b. Fülfûl … Midrârî hânedanına son verdi (366/976)' — YIL.",
     "ozet": "Zenâte'nin Miknâse koluna mensup Benî Midrâr'ın Sicilmâse'de kurduğu Sufrî hânedan; Endülüs Emevîleri adına hareket eden Mağrâve emîri Hazrûn b. Fülfûl'e yenilerek sona erdi. (kaynak: TDV, madde: midrariler)",
     "kaynak": "TDV: midrariler (MİDRÂRÎLER)",
     "kron": [
         ("0772-01-01", "kurulus", "Ebü'l-Kāsım b. Semkû Sicilmâse'de idareyi yeniden üstlendi; Midrârî hâkimiyeti başladı", "TDV midrariler: '(155/772)'"),
         ("0976-01-01", "son", "Mağrâve emîri Hazrûn b. Fülfûl Sicilmâse'yi alıp son Midrârî emîrini öldürdü; şehir Endülüs Emevîleri'ne geçti", "TDV midrariler: '(366/976)'"),
     ]},
    {"id": "hamdani-musul", "ad": "Hamdânîler (Musul kolu)", "tur": "hanedanlik", "bolge": "mezopotamya",
     "f": "0905-01-01", "t": "0979-01-01", "baskent": "Musul",
     "boya_gerekli": True,
     "ic_not_f": "TDV başlığı '905-1004' (iki kol birlikte); gövde: 'Ebü’l-Heycâ 293’te (905-906) Musul … valiliğine getirilmiştir' — YIL (293 H. = 905-906; 905 alındı). Kol ayrımı 929'dan sonradır ('Onun ölümünden sonra Hamdânîler iki ayrı kol halinde'); Halep kolu hamdani-halep (944) — örtüşmez.",
     "ic_not_t": "TDV: 'Remle Emîri Müferric b. Dağfel’e yenilerek öldürüldü (369/979); onun ölümüyle de Hamdânîler’in el-Cezîre ve Musul’daki hâkimiyetleri fiilen sona erdi' — YIL. Kardeşler 380/990'da Ukaylîler'ce bertaraf edildi (ukayli künyesi 990 — tutarlı).",
     "ozet": "Tağlib kabilesinden Hamdân ailesinin Musul ve el-Cezîre'de hüküm süren kolu; Büveyhî baskısı ve Ebû Tağlib Gazanfer'in ölümüyle fiilen sona erdi. (kaynak: TDV, madde: hamdaniler)",
     "kaynak": "TDV: hamdaniler (HAMDÂNÎLER)",
     "kron": [
         ("0905-01-01", "kurulus", "Ebü'l-Heycâ Abdullah b. Hamdân Musul valiliğine getirildi", "TDV hamdaniler: '293’te (905-906) Musul'"),
         ("0929-03-02", "hukumdar", "Ebü'l-Heycâ öldü; hânedan Musul ve Halep kollarına ayrıldı, Musul'da Nâsırüddevle Hasan öne çıktı", "TDV hamdaniler: '(17 Muharrem 317 / 2 Mart 929)'"),
         ("0979-01-01", "son", "Ebû Tağlib Gazanfer Remle'de öldürüldü; Hamdânîler'in Musul ve el-Cezîre hâkimiyeti fiilen sona erdi", "TDV hamdaniler: '(369/979)'"),
     ]},
    {"id": "hazar-kaganligi", "ad": "Hazar Kağanlığı", "tur": "hanlik", "bolge": "sibirya-bozkir",
     "f": "0630-01-01", "t": "0965-01-01", "baskent": "Belencer → İtil",
     "boya_gerekli": True,
     "ic_not_f": "TDV: 'Batı Göktürk Devleti yıkılınca Hazarlar bağımsızlıklarını ilân ettiler (630)' — YIL.",
     "ic_not_t": "⚠️ TDV devletin sonunu KESİN tarihlemiyor; başlık 'VII-XI. yüzyıllar'. Tek yıl: 'X. yüzyılda Ruslar karşısında güç duruma düşmeleri ve 965’te hakanın Hârizmliler’e sığınması'. t=965 bu cümleye dayanır ve 'devletin sonu' değil 'çöküşün ölçülebilir anı'dır. Koordinatör: kabul etmezse t'yi boş bırakmak şema izin vermiyorsa künyeyi bekletin.",
     "ozet": "Batı Göktürk Devleti'nin yıkılışıyla bağımsızlaşan, Karadeniz ile Hazar denizi arasındaki bozkırda ve İdil boyunda hüküm süren Türk devleti; Rus saldırıları karşısında çöktü. (kaynak: TDV, madde: hazarlar)",
     "kaynak": "TDV: hazarlar (HAZARLAR)",
     "kron": [
         ("0630-01-01", "kurulus", "Batı Göktürk Devleti yıkılınca Hazarlar bağımsızlıklarını ilân etti", "TDV hazarlar: '(630)'"),
         ("0965-01-01", "son", "Rus saldırıları karşısında Hazar hakanı Hârizmliler'e sığındı; kağanlık çöktü", "TDV hazarlar: '965’te hakanın Hârizmliler’e sığınması'"),
     ]},
    {"id": "uygur-kaganligi", "ad": "Uygur Kağanlığı (Ötüken)", "tur": "hanlik", "bolge": "sibirya-bozkir",
     "f": "0745-01-01", "t": "0840-01-01", "baskent": "Ordu-Balık (Ötüken)",
     "boya_gerekli": True,
     "ic_not_f": "TDV: '745 yılında Uygur yabgusu Basmıl kağanını …' — YIL. (742-743 Karluk-Basmıl-Uygur ittifakı Göktürk kağanı Ozmış'ı öldürür; TDV karluklar 'İkinci Göktürk Devleti’nin yıkılmasında (745)'.)",
     "ic_not_t": "TDV: '840 yılındaki Kırgız saldırısı kağanlığın sonunu getirdi' — YIL. Ardılı koco-uygur (911) künyede VAR; 840-911 arası Turfan/Kansu Uygur yapıları için ayrı künye açılmadı (bulunamadı bölümüne bakın).",
     "ozet": "İkinci Göktürk Devleti'nin yıkılışından sonra Basmıl kağanlığını deviren Uygur yabgusunun Ötüken'de kurduğu kağanlık; Kırgız saldırısıyla sona erdi. (kaynak: TDV, madde: uygurlar)",
     "kaynak": "TDV: uygurlar (UYGURLAR)",
     "kron": [
         ("0745-01-01", "kurulus", "Uygur yabgusu Basmıl kağanını yendi; Uygur Kağanlığı kuruldu", "TDV uygurlar: '745 yılında'"),
         ("0840-01-01", "son", "Kırgız saldırısı Uygur Kağanlığı'nın sonunu getirdi; Uygurlar dağıldı", "TDV uygurlar: '840 yılındaki Kırgız saldırısı kağanlığın sonunu getirdi'"),
     ]},
    {"id": "ziyadi", "ad": "Ziyâdîler (Yemen Tihâmesi)", "tur": "hanedanlik", "bolge": "arabistan",
     "f": "0818-01-01", "t": "1017-01-01", "baskent": "Zebîd",
     "boya_gerekli": True,
     "ic_not_f": "TDV: '202 (818) yılında isyanı bastırmak üzere' + başlık '(818-1017)' — YIL.",
     "ic_not_t": "TDV: 'Nefîs’in Ziyâdî hânedanının son temsilcisi … İbrâhim b. Abdullah’ı … öldürerek tahtı ele geçirmesiyle neticelendi (407/1017)' — YIL. Ardıl necahi künyesi 1022 (TDV '412/1022') — 1017-1022 Nefîs aralığı künyesiz (boşluk BEYAN).",
     "ozet": "Muhammed b. Abdullah b. Ziyâd'ın Abbâsî adına Yemen Tihâmesi'nde kurduğu hânedan; köle vezirlerin mücadelesinde son emîrin öldürülmesiyle sona erdi, yerini Necâhîler aldı. (kaynak: TDV, madde: ziyadiler)",
     "kaynak": "TDV: ziyadiler (ZİYÂDÎLER, Mustafa L. Bilge)",
     "kron": [
         ("0818-01-01", "kurulus", "Muhammed b. Ziyâd Tihâme isyanını bastırmak üzere Yemen'e gönderildi; Ziyâdî hânedanı kuruldu", "TDV ziyadiler: '202 (818)'"),
         ("1017-01-01", "son", "Köle Nefîs son Ziyâdî emîri İbrâhim b. Abdullah'ı öldürüp tahtı ele geçirdi", "TDV ziyadiler: '(407/1017)'"),
     ]},
]
