# -*- coding: utf-8 -*-
"""KRONO-KUZEY-0929 — YENİ maddelerin veri tablosu (üretici: ARAC-KRONO-KUZEY-0929-YAZ.py).

Kaynak damgası — GİZLENMİYOR:
  [özet] = Büyük Rus Ansiklopedisi (old.bigenc.ru / bigenc.ru), Britannica ve bazı
  kurumsal sayfalar bu oturumdan DOĞRUDAN AÇILAMADI (HTTP 401/403). Bilgi, arama
  motorunun o sayfadan çıkardığı özetten okundu; sayfa adresi yazıldı ki elle
  teyit edilebilsin. [özet] damgalı madde "sayfası okunarak doğrulandı" DEMEK DEĞİLDİR.
  TDV maddeleri (slug) ise GÖVDESİ ÇEKİLEREK okundu: denetim/KRONO-KUZEY-0929-tdv-onbellek/.

Takvim: kaynağın verdiği takvim ÇEVRİLMEDEN yazıldı (VERI-YAPISI §59); `gun:` alanı
takvimi söyler. Rus kaynakları 1918 öncesi Jülyen (eski üslup) verir.
"""

# ⚠️ 1775-06-15 "Zaporojye Seçi Rus ordusunca dağıtıldı" maddesi bu tabloda YOK:
#    üretimden SONRA data/kronoloji_cok_rusya.js'e elle eklendi (tabloya koymayı
#    unutmuştum). Yeniden üretilirse elle eklenmelidir.
OZ = " — sayfa açılamadı (401/403), arama özetinden okundu [özet]"

def m(t, b, tur, onem, dunya, kapsam, dev, etiket, yer, gun, d, kaynak):
    return dict(t=t, b=b, tur=tur, onem=onem, dunya=dunya, kapsam=kapsam, dev=dev,
                etiket=etiket, yer_id=yer, gun=gun, d=d, kaynak=kaynak)

E_SIB = ["kurulus", "sibirya", "genisleme", "konu-askeri", "konu-idari"]
E_SAV = ["savas", "toprak", "konu-askeri", "konu-siyasi"]
E_ANT = ["antlasma", "toprak", "konu-siyasi", "konu-diplomasi"]
BRE = "Bolşaya Rossiyskaya Entsiklopediya (BRE)"
IES = "Istoriçeskaya entsiklopediya Sibiri (2009)"

RUSYA = [
 # ── Moskova dönemi ─────────────────────────────────────────────────────
 m("1499-01-01", "Pustozersk kalesi kuruldu — Peçora ağzında ilk Moskova karakolu", "kurulus", 2, 1, "ic",
   "moskova", E_SIB, "Pustozersk", "1499 (kaynak yıl verir)",
   "III. İvan'ın kuzey seferi sırasında Peçora ırmağının aşağı kesiminde Pustozersk kalesi kuruldu. Kale, Ural ötesine ve Samoyed (Nenets) topraklarına yönelen Moskova ticaret ve vergi yolunun kuzeydeki dayanağı oldu.",
   BRE + ", \"Pustozersk\" old.bigenc.ru/domestic_history/text/3173524" + OZ),
 m("1500-07-14", "Vedroşa Muharebesi — Moskova, Litvanya ordusunu yendi; Bryansk ve Seversk toprakları Moskova'da kaldı", "savas", 4, 2, "dis",
   ["moskova", "litvanya-buyuk-dukalik"], E_SAV, "", "14 Temmuz 1500 (Jülyen — Rus kaynağı)",
   "1500-1503 Moskova-Litvanya savaşında Daniil Şçenya komutasındaki Moskova ordusu, Dorogobuj yakınında Vedroşa ırmağında Hatman Konstanty Ostrogski'nin ordusunu bozdu ve hatmanı esir aldı. Aynı yılın ilkbaharında alınan Bryansk ile Seversk şehirleri Moskova'nın elinde kaldı; savaşın sonunda Litvanya topraklarının yaklaşık üçte biri Moskova'ya geçmişti.",
   "Rusya Savunma Bakanlığı Askerî Ansiklopedisi, \"Забытая победа на Ведроши\" (encyclopedia.mil.ru)" + OZ),
 m("1514-08-01", "Smolensk Moskova'ya teslim oldu — III. Vasili şehre girdi", "toprak-kazanc", 4, 2, "dis",
   ["moskova", "litvanya-buyuk-dukalik"], E_SAV, "Smolensk", "31 Temmuz teslim, 1 Ağustos 1514 giriş (Jülyen)",
   "1512-1522 Moskova-Litvanya savaşının üçüncü kuşatmasında Litvanya garnizonu 31 Temmuz'da teslim oldu; Moskova ordusu 1 Ağustos'ta şehre törenle girdi ve halk III. Vasili'ye bağlılık yemini etti. Smolensk, Vasili'nin batıdaki en büyük kazancıdır; birkaç hafta sonra Orşa'da uğranan yenilgi şehri geri aldırmadı.",
   "\"К вопросу о «Смоленском взятии» 1514 г.\", CyberLeninka akademik makale (cyberleninka.ru/article/n/k-voprosu-o-smolenskom-vzyatii-1514-g)" + OZ),
 # ── Sibirya'ya ilerleyiş (Çarlık) ─────────────────────────────────────
 m("1594-01-01", "Tara kalesi kuruldu — İrtiş boyunda Küçüm Han'a karşı ileri karakol", "kurulus", 2, 1, "dis",
   "rusya", E_SIB, "Tara", "1594 (kaynak yıl verir)",
   "Sibir Hanlığı'nın son hanı Küçüm'e karşı İrtiş'in orta kesiminde Tara kalesi yapıldı. Kale, bozkırla orman kuşağı arasındaki Rus hâkimiyetinin güneydeki dayanağı oldu.",
   BRE + ", \"Omskaya oblast\" old.bigenc.ru/geography/text/2689005" + OZ),
 m("1595-01-01", "Obdorsk ostrogu kuruldu — Ob ağzında Rus karakolu (bugünkü Salehard)", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Obdorsk (Salehard)", "1595 (kaynak yıl verir; kışlak 1593)",
   "Ob ırmağının ağzına yakın Obdorsk'ta 1593'te kurulan kışlak, 1595'te ostroga (ahşap kale) dönüştürüldü. Kale Yamal ve aşağı Ob'daki yerli halktan kürk vergisi (yasak) toplamak için kullanıldı.",
   BRE + ", \"Salehard\" old.bigenc.ru/geography/text/3528963" + OZ),
 m("1601-01-01", "Mangazeya kuruldu — Taz ırmağında kutup ötesi kürk ticaret merkezi", "kurulus", 2, 1, "ic",
   "rusya", E_SIB, "Mangazeya", "1601 (kaynak yıl verir)",
   "Taz ırmağı kıyısında kurulan Mangazeya, XVII. yüzyılın ilk yarısında Batı Sibirya kürk ticaretinin kuzeydeki merkezi oldu. Deniz yolunun 1619'da yasaklanması ve yangınlardan sonra şehir 1672'de terk edildi.",
   BRE + ", \"Mangazeya\" old.bigenc.ru/domestic_history/text/2156295" + OZ),
 m("1604-01-01", "Tomsk kalesi kuruldu", "kurulus", 3, 1, "ic",
   "rusya", E_SIB, "Tomsk", "1604 (kaynak yıl verir)",
   "Tom ırmağı kıyısında Tomsk kalesi kuruldu. Kale Ob-Yenisey arasındaki bölgenin idari ve askerî merkezi oldu; Rusların doğuya ve güneye ilerleyişi bir süre buradan yönetildi.",
   BRE + ", \"Tomsk\" old.bigenc.ru/geography/text/4196538; Encyclopaedia Britannica \"Tomsk\"" + OZ),
 m("1607-01-01", "Turuhansk kışlağı kuruldu — Yenisey'in aşağı kesiminde", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Turuhansk", "1607 (kaynak yıl verir)",
   "Yenisey'in aşağı kesiminde Turuhansk kışlağı kuruldu. Kışlak, Mangazeya'dan doğuya uzanan kürk yolunun Yenisey'deki durağıydı.",
   BRE + ", \"Yenisey\" bigenc.ru/c/enisei-9ea096" + OZ),
 m("1618-01-01", "Kuznetsk kışlağı kuruldu — Tom'un yukarısında (bugünkü Novokuznetsk)", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Kuznetsk", "1618 ilkbahar (kaynak ay verir, gün vermez); ostrog 1620",
   "Tom ırmağının yukarı kesiminde, demirci Şor halkının yurdunda Kuznetsk kışlağı kuruldu; 1620'de ostroga dönüştü. Adı yerli halkın demircilik ustalığından gelir.",
   BRE + ", \"Novokuznetsk\" old.bigenc.ru/geography/text/2667811" + OZ),
 m("1619-01-01", "Yeniseysk ostrogu kuruldu", "kurulus", 2, 1, "ic",
   "rusya", E_SIB, "Yeniseysk", "1619 (kaynak yıl verir)",
   "Yenisey kıyısında kurulan Yeniseysk ostrogu, Lena ve Baykal yönündeki Rus keşif ve fetih seferlerinin çıkış noktası oldu.",
   BRE + ", \"Yenisey\" bigenc.ru/c/enisei-9ea096" + OZ),
 m("1628-01-01", "Krasnoyarsk ostrogu kuruldu", "kurulus", 3, 1, "ic",
   "rusya", E_SIB, "Krasnoyarsk", "1628 (kaynak yıl verir)",
   "Andrey Dubenskoy komutasındaki Kazaklar Yenisey'in orta kesiminde Krasnıy Yar (Krasnoyarsk) ostrogunu kurdu. Kale güneydeki Kırgız ve bozkır halklarına karşı sınır dayanağı oldu.",
   BRE + ", \"Krasnoyarsk\" old.bigenc.ru/geography/text/2107402" + OZ),
 m("1630-01-01", "İlimsk kışlağı kuruldu — Yenisey'den Lena'ya geçiş yolunda", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "İlimsk (Ilimskiy ostrog)", "1630 (kaynak yıl verir); ostrog 1640/1647",
   "İvan Galkin İlim ırmağında bir kışlak kurdu. Yer, Yenisey havzasından Lena havzasına geçen taşıma yolunun anahtarıydı; 1640'larda ostroga dönüştü.",
   IES + ", \"Ilimsk\" (irkipedia.ru)" + OZ),
 m("1632-01-01", "Jigansk kışlağı kuruldu — Lena'nın aşağı kesiminde", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Jigansk", "1632 (kaynak yıl verir)",
   "Lena'nın aşağı kesiminde Jigansk kışlağı kuruldu. Kışlak, aynı yıl kurulan Yakutsk'tan kuzeye, Lena ağzına ve Yana'ya uzanan yolun durağı oldu.",
   BRE + ", \"Lena\" bigenc.ru/c/lena-reka-dfef5c" + OZ + " — orta güven"),
 m("1632-09-25", "Yakutsk (Lena) ostrogu kuruldu — Pyotr Beketov", "kurulus", 3, 1, "ic",
   "rusya", E_SIB, "Yakutsk", "25 Eylül 1632 (Jülyen; kaynak Gregoryen karşılığını 5 Ekim verir)",
   "Yüzbaşı Pyotr Beketov Lena kıyısında Lenski ostrogunu kurdu. Yakutsk kısa sürede Doğu Sibirya'nın idari merkezi oldu; kale 1634 ve 1643'te yer değiştirdi.",
   BRE + ", \"Yakutsk\" old.bigenc.ru/geography/text/5768359" + OZ),
 m("1634-01-01", "Vilyuysk kışlağı kuruldu", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Vilyuysk", "1634 (kaynak yıl verir)",
   "Lena'nın sol kolu Vilyuy üzerinde Vilyuysk kışlağı kuruldu; batıdaki Tunguz (Evenk) topraklarından vergi toplanan noktalardan biri oldu.",
   BRE + ", \"Vilyuy\" bigenc.ru/c/viliui-ddd14a" + OZ + " — orta güven"),
 m("1635-07-17", "Olyokminsk ostrogu kuruldu — Pyotr Beketov", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Olyokminsk", "17 Temmuz 1635 (Rus kaynağı, Jülyen); kışlak 1633",
   "Olyokma'nın Lena'ya kavuştuğu yerde 1633'te kurulan kışlak, Pyotr Beketov tarafından ostroga dönüştürüldü.",
   BRE + ", \"Olyokminsk\" old.bigenc.ru/geography/text/5768280" + OZ),
 m("1636-04-17", "Tambov kalesi kuruldu — Belgorod savunma hattının doğu ucu", "kurulus", 2, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Tambov", "17 Nisan 1636 (Jülyen; kaynak Gregoryen karşılığını 27 Nisan verir)",
   "Voyvoda Roman Boborıkin Tsna ırmağı kıyısında Tambov kalesini kurdu. Kale, Kırım ve Nogay akınlarına karşı bozkır kenarında kurulan müstahkem hattın doğu kanadını tuttu.",
   BRE + ", \"Tambov\" old.bigenc.ru/geography/text/4180917" + OZ),
 m("1637-01-01", "Samarovo yamı kuruldu — İrtiş-Ob kavşağında (bugünkü Hantı-Mansiysk)", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Samarovo", "1637 (kaynak yıl verir)",
   "İrtiş'in Ob'a kavuştuğu yerde posta ve menzil durağı (yam) olarak Samarovo kuruldu.",
   BRE + ", \"Hantı-Mansiysk\" old.bigenc.ru/geography/text/4729366" + OZ),
 m("1638-01-01", "Verhoyansk kurulduğu yıl — Yana ırmağında Rus karakolu", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Verhoyansk", "1638 (kaynak yıl verir)",
   "Postnik İvanov'un seferiyle Yana ırmağı boyunda Verhoyansk kurulmaya başlandı; Yana ve İndigirka havzasına uzanan kürk vergisi ağının parçası oldu.",
   "Encyclopaedia Britannica, \"Verkhoyansk\"" + OZ),
 m("1639-01-01", "Zaşiversk ostrogu kuruldu — İndigirka üzerinde", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Zaşiversk", "1639 (kaynak yıl verir)",
   "Postnik İvanov İndigirka üzerinde Zaşiversk ostrogunu kurdu; kale XVIII. yüzyılın sonuna kadar bölgenin vergi merkeziydi.",
   BRE + ", \"İndigirka\" bigenc.ru/c/indigirka-75e334" + OZ),
 m("1641-01-01", "Açinsk ostrogu kuruldu", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Açinsk", "1641 (kaynak yıl verir)",
   "Beyaz İyus ırmağı üzerinde Açinsk ostrogu kuruldu; güneydeki Kırgız akınlarına karşı sınır kalelerinden biriydi, 1683 yangınından sonra yeri değiştirildi.",
   BRE + ", \"Açinsk\" old.bigenc.ru/geography/text/3923593" + OZ),
 m("1643-01-01", "Srednekolımsk kışlağı kuruldu — Kolıma'ya ilk Rus yerleşimi", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Srednekolımsk", "1643 yazı (kaynak mevsim verir, gün vermez)",
   "Mihail Stadukhin ve Dmitri Zıryan'ın öncüleri Kolıma ırmağının orta kesiminde kışlak kurdu; bu, Rusların Kolıma havzasındaki ilk kalıcı noktasıdır.",
   BRE + ", \"Srednekolımsk\" old.bigenc.ru/geography/text/5768310" + OZ),
 m("1644-01-01", "Nijnekolımsk kışlağı kuruldu — Kolıma ağzında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Nijnekolımsk", "1644 (kaynak yıl verir)",
   "Kolıma'nın aşağı kesiminde kurulan kışlak, Doğu Sibirya Denizi kıyısı boyunca doğuya yapılan seferlerin (1648 Dejnyov) çıkış noktası oldu.",
   IES + ", \"Nijnekolımsk\" (bsk.nios.ru)" + OZ),
 m("1647-01-01", "Verhneangarsk ostrogu kuruldu — Baykal'ın kuzey ucunda", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Verhneangarsk ostrogu", "1647 (kaynak yıl verir; kışlak 1643/1646 da anılır)",
   "Yukarı Angara'nın Baykal'a döküldüğü yerde ostrog kuruldu; Baykal ötesine (Buryat ve Evenk yurtlarına) açılan kuzey kapısı oldu.",
   IES + ", \"Verhneangarskiy ostrog\" (irkipedia.ru)" + OZ),
 m("1647-05-23", "Ohotsk kışlağı kuruldu — Rusya Pasifik kıyısına ulaştı", "kurulus", 3, 2, "ic",
   "rusya", E_SIB, "Ohotsk", "23 Mayıs 1647 (Rus kaynağı, Jülyen); ostrog 1649",
   "Semyon Şelkovnikov'un Kazakları Ohota ırmağının ağzında kışlak kurdu. Ohotsk, Rusya'nın Pasifik kıyısındaki ilk kalıcı noktası ve sonraki yüzyılda Kamçatka ile Alaska seferlerinin limanı oldu.",
   "Ohotsk Bölgesi idaresi resmî tarih sayfası (admokhotsk.khabkrai.ru)" + OZ),
 m("1648-01-01", "Barguzin ostrogu kuruldu — Baykal'ın doğu kıyısında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Barguzin", "1648 (kaynak yıl verir)",
   "Barguzin ırmağı üzerinde kurulan ostrog, Baykal ötesinde (Transbaykal) kurulan ilk Rus kalesidir.",
   BRE + ", \"Ostrog\" old.bigenc.ru/fine_art/text/5743212" + OZ),
 m("1648-10-14", "Nijneudinsk kışlağı kuruldu", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Nijneudinsk", "14 Ekim 1648 (Pokrov günü — Rus kaynağı, Jülyen); ostrog 1649",
   "Uda ırmağı üzerinde bir devlet kışlağı kuruldu; ertesi yıl ostroga dönüştü. Yer, Yenisey'den Baykal'a giden yolun durağıydı.",
   "İrkutsk Bölge Kütüphanesi yayınları (lib38.ru) ve pribaikal.ru" + OZ + " — zayıf-orta güven"),
 m("1652-01-01", "Ostrogojsk kalesi kuruldu — bozkır savunma hattında", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Ostrogojsk", "1652 (kaynak yıl verir)",
   "Voyvoda F. Arsenyev Tihaya Sosna ırmağı üzerinde Ostrogojsk kalesini kurdu; kaleye Hmelnitski ayaklanmasından kaçan Ukraynalı Kazaklar yerleştirildi.",
   "Ostrogojsk belediyesi resmî sayfası (ostrogozhsk-r20.gosweb.gosuslugi.ru)" + OZ),
 m("1653-01-01", "Şilka (Nerçinsk) ostrogu kuruldu — Amur'un yukarı havzasında", "kurulus", 2, 1, "ic",
   "rusya", E_SIB, "Nerçinsk", "1653 (kaynak yıl verir); Nerçinsk adı 1658-1659",
   "Pyotr Beketov'un adamları Şilka üzerinde bir ostrog kurdu. Kale 1656'da yandı, 1658'de Nerça ağzında yeniden yapıldı ve Nerçinsk adını aldı; 1689 Rus-Çin antlaşması burada imzalandı.",
   BRE + ", \"Nerçinsk\" old.bigenc.ru/domestic_history/text/5292416" + OZ),
 m("1654-01-01", "Balagansk ostrogu kuruldu — Angara üzerinde", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Balagansk", "Mayıs-Haziran 1654 (kaynak ay verir, gün vermez)",
   "Dmitri Firsov Angara üzerinde, Buryat yurdunun ortasında Balagansk ostrogunu kurdu.",
   IES + ", \"Balaganskiy ostrog\" (irkipedia.ru)" + OZ),
 m("1661-01-01", "İrkutsk ostrogu kuruldu", "kurulus", 3, 1, "ic",
   "rusya", E_SIB, "İrkutsk", "1661 (kaynak yıl verir; kışlak 1652)",
   "Yakov Pohabov Angara kıyısında İrkutsk ostrogunu kurdu. İrkutsk XVIII. yüzyılda Doğu Sibirya'nın ve Çin ticaretinin merkezi oldu.",
   "Encyclopaedia Britannica, \"Irkutsk\"" + OZ),
 m("1662-01-01", "Şadrinsk slobodası kuruldu — Trans-Ural'da", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Şadrinsk", "1662 (kaynak yıl verir)",
   "İset ırmağı üzerinde köylü yerleşimi (sloboda) olarak Şadrinsk kuruldu; Trans-Ural tarım kuşağının genişlemesinin parçasıdır.",
   BRE + ", \"Şadrinsk\" old.bigenc.ru/geography/text/4689676" + OZ),
 m("1665-01-01", "Selenginsk ostrogu kuruldu — Moğol sınırına doğru", "kurulus", 1, 1, "dis",
   "rusya", E_SIB, "Selenginsk", "1665 (kaynak yıl verir)",
   "Selenga ırmağı üzerinde kurulan ostrog, Rusların Moğol hanlıklarıyla ve Qing ile temas ettiği güney sınırının kalesi oldu.",
   BRE + ", \"Selenginsk\" old.bigenc.ru/geography/text/5619751" + OZ),
 m("1667-01-01", "Dudinka yasak kışlağı kuruldu — Yenisey'in ağzına yakın", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Dudinka", "1667 (kaynak yıl verir)",
   "Yenisey'in aşağı kesiminde, yerli halktan kürk vergisi toplamak için Dudinka kışlağı kuruldu.",
   BRE + ", \"Dudinka\" old.bigenc.ru/geography/text/1969887; Encyclopaedia Britannica \"Dudinka\"" + OZ),
 m("1668-01-01", "Kamışlov ostrogu kuruldu — Trans-Ural'da", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Kamışlov", "Ağustos-Kasım 1668 (kaynak ay aralığı verir)",
   "Pışma ırmağı kıyısında Kamışlov slobodası ve ostrogu kuruldu; Tobol havzasına yerleşen Rus köylülerini Başkurt ve Kalmuk akınlarına karşı koruyordu.",
   "Kamışlov belediyesi resmî tarih sayfası (gorod-kamyshlov.ru)" + OZ),
 m("1679-01-01", "Udskoy ostrogu kuruldu — Ohotsk Denizi'nin güneybatısında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Udskoy ostrogu", "1679 (kaynak yıl verir)",
   "Danila Mihaylov Uda ırmağı üzerinde kışlak kurdu; yer, Amur'un kuzeyinde Qing sınırına yakın Rus varlığının dayanağı oldu.",
   IES + ", \"Udskiy ostrog\" (bsk.nios.ru)" + OZ),
 m("1692-01-01", "Yama kışlağı kuruldu — Ohotsk Denizi'nin kuzey kıyısında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Yama zimovyesi", "1692 (kaynak yıl verir)",
   "İvan Antipin Solovey Yama ırmağında kışlak kurdu; bu, kuzey Ohotsk kıyısındaki ilk belgeli Rus yerleşimidir (Yamsk ostrogu 1739).",
   "A. S. Zuev, \"Русские остроги на крайнем Северо-Востоке\" (zaimka.ru)" + OZ),
 m("1697-01-01", "Nijnekamçatsk kışlağı kuruldu — Atlasov'un Kamçatka seferi", "kurulus", 2, 1, "ic",
   "rusya", E_SIB, "Nijnekamçatsk", "1697 sonbaharı (kaynak mevsim verir)",
   "Vladimir Atlasov'un Kamçatka seferinde Yolovka ağzında kışlak kuruldu; Kamçatka'daki Rus varlığının başlangıcıdır.",
   IES + ", \"Nijnekamçatskiy ostrog\" (bsk.nios.ru)" + OZ),
 m("1704-01-01", "Bolşeretsk ostrogu kuruldu — Kamçatka'nın batı kıyısında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Bolşeretsk", "1704 (kaynak yıl verir; bir kaynak 1703)",
   "Bolşaya ırmağı üzerinde kurulan ostrog, Ohotsk'tan deniz yoluyla gelen gemilerin Kamçatka'daki iskelesi oldu.",
   IES + ", \"Bolşeretskiy ostrog\" (bsk.nios.ru)" + OZ),
 m("1707-01-01", "Abakan ostrogu kuruldu — Yenisey'in yukarısında", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Abakan ostrogu", "1707 (kaynak yıl verir; I. Petro fermanı 1706)",
   "I. Petro'nun fermanıyla Yenisey'in yukarı kesiminde Abakan ostrogu yapıldı; Kırgızların güneye göçüyle boşalan Minusinsk çukurunun Ruslarca iskânı başladı.",
   "Letopis Yeniseyskoy Sibiri (bölgesel tarih yayını)" + OZ + " — orta güven"),
 m("1709-01-01", "Penjinsk ostrogu kuruldu — Koryak yurdunda", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Penjinsk ostrogu", "1709 (kaynak yıl verir)",
   "Kazaklar Penjina ırmağı üzerinde ostrog kurdu; Koryak direnişi karşısında kale 1710'ların sonunda yıkıldı.",
   IES + ", \"Koryakskiy avtonomnıy okrug\" (bsk.nios.ru)" + OZ),
 m("1714-01-01", "Olyutorsk (Arhangelsk) ostrogu kuruldu", "kurulus", 1, 1, "ic",
   "rusya", E_SIB, "Olyutorsk (Arhangelsk)", "1714 (kaynak yıl verir)",
   "A. Petrov Olyutor ırmağında Arhangelsk ostrogunu kurdu; kale Koryak baskısıyla 1715'te terk edildi.",
   "A. S. Zuev, \"Русские остроги на крайнем Северо-Востоке\" (zaimka.ru)" + OZ),
 m("1718-01-01", "Semipalatinsk kalesi kuruldu — İrtiş hattı Cungar sınırına ilerledi", "kurulus", 2, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Semipalatinsk", "1718 (kaynak yıl verir)",
   "İrtiş üzerinde, Cungar Hanlığı'nın kuzey ucunda Semipalatinsk kalesi kuruldu; Omsk'tan güneye inen İrtiş müstahkem hattının halkalarından biridir.",
   "Semey şehri tarih sayfası ve Semey kütüphanesi (semey.city, semeylib.kz)" + OZ),
 m("1720-01-01", "İrtiş hattı: Koryakovsk forpostu (Pavlodar) ve Ust-Kamenogorsk kalesi kuruldu", "kurulus", 2, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Ust-Kamenogorsk", "1720 — Ust-Kamenogorsk Ağustos 1720 (kaynak ay verir)",
   "İvan Liharev'in İrtiş seferinde Ust-Kamenogorsk kalesi kuruldu; aynı yıl aşağıda Koryakovsk forpostu (bugünkü Pavlodar) yapıldı. İki nokta İrtiş hattını Cungar yurduna, Altay eteklerine kadar uzattı.",
   BRE + ", \"Ust-Kamenogorsk\" bigenc.ru/c/ust-kamenogorsk-adae90; Entsiklopediya geografiçeskih nazvaniy, \"Koryakovskiy forpost\"" + OZ),
 m("1722-01-01", "Nijni Tagil demir fabrikasının kuruluş yılı", "kurulus", 1, 1, "ic",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Nijniy Tagil", "1722 (kaynak 'geleneksel kuruluş tarihi' der)",
   "Demidov ailesinin Ural'daki fabrika ağının parçası olarak Tagil ırmağı üzerinde demir işletmesi kuruldu; şehir bu fabrikanın çevresinde büyüdü.",
   BRE + ", \"Nijniy Tagil\" old.bigenc.ru/geography/text/2267348" + OZ),
 m("1722-07-27", "I. Petro Ağrahan Körfezi'ne çıktı — Hazar seferi Dağıstan kıyısında", "savas", 3, 2, "dis",
   ["rusya", "safevi"], E_SAV, "Ağraham burnu", "27 Temmuz 1722 (Jülyen; Gregoryen karşılığı 7 Ağustos — hesap)",
   "Astrahan'dan denize açılan Rus donanması Ağrahan Körfezi'ne girdi; I. Petro burada karaya çıkıp bir tahkimat (Ağrahan retranşmanı) yerini seçti ve kuvvetlerini Derbend'e doğru yürüttü.",
   "Rusya Devlet Donanma Arşivi, \"Персидский поход 1722-1723 гг.\" (rgavmf.ru)" + OZ),
 m("1723-05-04", "Yegoşiha bakır fabrikası kuruldu — Perm'in resmî kuruluş günü", "kurulus", 1, 1, "ic",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Perm", "4 Mayıs 1723 (Jülyen; kaynak Gregoryen karşılığını 15 Mayıs verir)",
   "Kama kıyısında Yegoşiha bakır fabrikasının kurulmasıyla Perm'in çekirdeği oluştu; bu gün şehrin resmî kuruluş tarihi sayılır.",
   BRE + ", \"Perm\" bigenc.ru/c/perm-4ec59c" + OZ),
 m("1723-11-07", "Yekaterinburg fabrikası çalışmaya başladı — Ural madencilik merkezi", "kurulus", 2, 1, "ic",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Yekaterinburg", "7 Kasım 1723 (Jülyen; kaynak Gregoryen karşılığını 18 Kasım verir); resmî açılış 24 Kasım",
   "Vasili Tatişçev ve Georg Wilhelm de Gennin'in kurduğu İset demir fabrikasının ilk atölyesi çalışmaya başladı. Yekaterinburg, Ural maden idaresinin merkezi oldu.",
   BRE + ", \"Yekaterinburg\" old.bigenc.ru/geography/text/3834279" + OZ),
 m("1730-01-01", "Barnaul — Altay'da Demidov yerleşiminin resmî kuruluş yılı", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Barnaul", "1730 resmî tarih (1980'de belirlendi); araştırmacıların bir kısmı 1739 der",
   "Akinfi Demidov'un Altay'daki bakır işletmeleri Cungar sınırına yakın bölgeye Rus yerleşimini taşıdı; Barnaul'un resmî kuruluş yılı 1730, fabrika inşası 1739'dur.",
   "Altay Kray resmî portalı (altairegion22.ru)" + OZ + " — tarih tartışmalı"),
 m("1736-01-01", "Zmeinogorsk gümüş madeni bulundu — Altay'da", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Zmeinogorsk", "1736 (kaynak yıl verir; kale 1744)",
   "Altay'da Zmeinaya dağında zengin gümüş yatağı bulundu ve maden kuruldu; kalıcı yerleşim ve kale 1744'te yapıldı.",
   "Altay Kray Bilimsel Kütüphanesi (akunb.altlib.ru)" + OZ + " — orta güven"),
 m("1736-09-13", "Çelyabinsk kalesi kuruldu — Başkurt yurdunda Orenburg seferi", "kurulus", 2, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Çelyabinsk", "13 Eylül 1736 (kaynak; takvim belirtilmemiş — atlas kaydı 2 Eylül)",
   "Orenburg seferi sırasında Albay Aleksey Tevkelev, Miass ırmağı kıyısındaki Çelyabi mevkiinde kale kurdu; kale Başkurt ayaklanmalarına karşı Ural ötesi yolunu korudu.",
   "Güney Ural Devlet Üniversitesi, \"Челябинская крепость\" (natu.susu.ru)" + OZ),
 m("1762-01-01", "Gorbitsa sınır karakolu kuruldu — Qing sınırında", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Gorbitsa (Gorbiçenskaya)", "1762 (kaynak yıl verir)",
   "Nerçinsk Antlaşması'nın çizdiği Rus-Qing sınırında, Şilka üzerinde Gorbitsa sınır karakolu kuruldu.",
   "Entsiklopediya Zabaykalya, \"Gorbitsa\" (ez.chita.ru)" + OZ),
 m("1765-01-01", "Akşa sınır kalesi kuruldu — Onon üzerinde", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Akşa (Akşinsk kalesi)", "1765 (kaynak yıl verir; inşa 1765-1772)",
   "Onon ırmağı üzerinde Moğolistan (Qing) sınırını gözetmek için Akşa kalesi kuruldu.",
   "Entsiklopediya Zabaykalya, \"Akşa\" (ez.chita.ru)" + OZ),
 m("1784-01-01", "Şelihov, Kodiak'ta Üç Aziz Körfezi yerleşimini kurdu — Alaska'da ilk kalıcı Rus yerleşimi", "kurulus", 3, 2, "dis",
   ["rusya"], ["kurulus", "alaska", "konu-idari"], "Üç Aziz Körfezi (Trekh Svyatiteley)", "Ağustos 1784 (kaynak ay verir, gün vermez)",
   "Grigori Şelihov'un şirketi Kodiak adasında Üç Aziz Körfezi'nde yerleşim kurdu; bu, Alaska'daki ilk kalıcı Rus yerleşimidir. Merkez 1792'de Pavlovskaya limanına taşındı.",
   "ABD Millî Park Servisi, \"Three Saints Bay Site\" (nps.gov/places/three-saints-bay-site.htm)" + OZ),
 m("1791-01-01", "Kenai'de Aziz Nikola Redutu kuruldu — Alaska", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-idari"], "Kenai (Nikolayevskiy Redut)", "1791 (kaynak yıl verir)",
   "Lebedev-Lastoçkin şirketinin avcıları Kenai yarımadasında Aziz Nikola (Nikolayevski) redutunu kurdu.",
   "SAH Archipedia (Society of Architectural Historians); A. Boraas, Concise History of the Kenai Peninsula" + OZ),
 m("1796-01-01", "Yakutat'ta Novorossiysk yerleşimi kuruldu — Alaska", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-idari"], "Yakutat (Novorossiysk)", "Haziran 1796 (kaynak ay verir)",
   "Aleksandr Baranov'un yönetimindeki Rus-Amerika şirketi öncülleri Yakutat'a yerleşimciler çıkardı; koloni Tlingit saldırısıyla 1805'te yok oldu.",
   "Encyclopaedia Britannica, \"Aleksandr Andreyevich Baranov\"" + OZ),
 m("1824-04-08", "Karkaralı ve Kökçetav dış okrugları açıldı — Orta Cüz'de hanlık kalktı", "idari", 2, 1, "dis",
   ["rusya", "kazak-hanligi"], ["idari", "ilhak", "konu-idari"], "Karkaralinsk (Karkaralı)", "8 Nisan 1824 Karkaralı açılış emri (kaynak); Kökçetav 29 Nisan 1824 — takvim belirtilmemiş",
   "1822 Sibirya Kırgızları Nizamnamesi uyarınca Orta Cüz topraklarında ilk dış okruglar açıldı: Karkaralı ve Kökçetav. Hanlık idaresi kaldırılıp yerine Rus denetimindeki sultan-okrug düzeni geldi.",
   "Kazakistan resmî tarih portalı (e-history.kz); inkaraganda.kz" + OZ),
 m("1833-01-01", "Mihaylovski Redutu (St. Michael) kuruldu — Norton Körfezi", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-idari"], "Mihaylovskiy Redut (St. Michael)", "1833 (kaynak yıl verir)",
   "Ferdinand von Wrangel'in emriyle Mihail Tebenkov Norton Körfezi'nde redut kurdu; Yukon havzasına açılan ticaret yolunun başıydı.",
   "ABD Kongre Kütüphanesi (loc.gov) koleksiyon notu" + OZ),
 m("1834-01-01", "Aziz Dionisiy Redutu kuruldu — Stikine ağzı (bugünkü Wrangell)", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-idari"], "Wrangell (Redut Sv. Dionisiy)", "1834 (kaynak yıl verir)",
   "Rus-Amerika Şirketi, İngiliz Hudson Körfezi Şirketi'nin Stikine ırmağına girişini önlemek için redut kurdu; yer 1840'ta kira sözleşmesiyle İngiliz şirketine bırakıldı.",
   "Wrangell şehri resmî sayfası (wrangell.com)" + OZ),
 m("1838-01-01", "Nulato ticaret karakolu kuruldu — Yukon üzerinde", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-ekonomi"], "Nulato", "1838 (kaynak yıl verir; bir kaynak 1839)",
   "Pyotr Malahov Yukon ırmağı üzerinde Nulato karakolunu kurdu; Rus-Amerika Şirketi'nin iç Alaska'daki en uzak noktasıydı.",
   "Arctic dergisi (Arctic Institute of North America), \"Trading Posts along the Yukon River\"" + OZ),
 m("1841-01-01", "Kolmakovski Redutu kuruldu — Kuskokwim üzerinde", "kurulus", 1, 1, "dis",
   "rusya", ["kurulus", "alaska", "konu-ekonomi"], "Kolmakovskiy Redut", "1841 (kaynak yıl verir)",
   "Rus-Amerika Şirketi Kuskokwim ırmağı üzerinde Kolmakovski redutunun inşasına başladı.",
   "University of Alaska Museum of the North, \"Kolmakovsky Redoubt\" (uaf.edu)" + OZ),
 m("1858-05-28", "Aigun Antlaşması — Qing, Amur'un sol kıyısını Rusya'ya bıraktı", "antlasma", 4, 3, "dis",
   ["rusya", "qing-hanedani"], E_ANT, "Aigun", "28 Mayıs 1858 (Gregoryen; Jülyen 16 Mayıs)",
   "Doğu Sibirya genel valisi Nikolay Muravyov ile Qing komutanı Yishan'ın Aigun'da imzaladığı antlaşmayla Argun'dan denize kadar Amur'un sol kıyısı Rusya'ya bırakıldı; Albazin, Blagoveşçensk ve Amur ağzındaki Nikolayevsk bu sınırın Rus yakasında kaldı. Ussuri ile deniz arasındaki bölge 1860 Pekin Antlaşması'yla Rusya'ya geçti.",
   "TDV \"rusya\" (yıl: \"1858'de yapılan bir antlaşmayla Amur nehrinin sol kıyıları Rusya'ya bırakıldı\"); gün: Encyclopaedia Britannica \"Treaty of Aigun\" ve Rusya Cumhurbaşkanlığı Kütüphanesi (prlib.ru/en/history/619270)" + OZ),
 m("1858-05-31", "Kazakeviçevo (Ust-Ussuriysk) stanitsası adını aldı — Amur-Ussuri kavşağı", "kurulus", 1, 1, "dis",
   "rusya", E_SIB, "Kazakevičevo (Kazakevičeva stanitsası)", "31 Mayıs 1858 (köy idaresinin resmî kuruluş günü; takvim belirtilmemiş); karakol 1857",
   "Aigun'dan hemen sonra Amur ile Ussuri'nin kavşağında 1857'de kurulan Ust-Ussuriysk karakolu Kazak stanitsası yapıldı ve Kazakeviçevo adını aldı.",
   "Kazakeviçevo köy idaresi resmî tarih sayfası (kazakevichevo.khabkrai.ru)" + OZ),
 m("1864-01-01", "Bodaybo altın madeni merkezi kuruldu — Vitim havzası", "kurulus", 1, 1, "ic",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Bodaybo", "1864 (kaynak yıl verir)",
   "Lena-Vitim altın yataklarında maden yönetimi (Bodaybinskaya rezidentsiya) kuruldu; bölge 1912 Lena katliamıyla anılacaktır.",
   "Bodaybo ilçe idaresi resmî tarih sayfası (uprava-bodaibo.ru)" + OZ),
 m("1864-06-12", "Türkistan (Yesi) şehri Rus kuvvetlerince alındı", "toprak-kazanc", 3, 2, "dis",
   ["rusya", "hokand"], E_SAV, "Türkistan (Yesi)", "12 Haziran 1864 (kaynak; takvim belirtilmemiş)",
   "Albay Verevkin komutasındaki Sirderya kolu, Hokand Hanlığı'na bağlı Türkistan şehrini ve Hoca Ahmed Yesevî türbesini ele geçirdi.",
   "\"Türkistan Askerî Valiliğinin Kurulması ve Sınırlarının Belirlenmesi\", Bilig (Ahmet Yesevi Üniversitesi, bilig.yesevi.edu.tr)" + OZ),
 m("1864-09-22", "Çimkent Rus ordusunca alındı — Hokand'ın sınır kaleleri düştü", "toprak-kazanc", 3, 2, "dis",
   ["rusya", "hokand"], E_SAV, "Çimkent", "22 Eylül 1864 (kaynak; takvim belirtilmemiş)",
   "Çernyayev'in 7 Temmuz'daki ilk hücumu püskürtülmüştü; Âlim Kul'un ana kuvvetleriyle ayrılmasından sonra şehir savunucuları teslim olmak zorunda kaldı. Çimkent'in düşüşüyle Sirderya ve Yedisu hatları birleşti, yol Taşkent'e açıldı.",
   "TDV \"cimkent\" (ilk hücum 7 Temmuz 1864, teslim; gün vermez); gün: \"Çarlık Rusyası'nın Türkistan'da Hâkimiyet Kurması\" (dergipark.org.tr)" + OZ),
 m("1866-05-24", "Hucend fırtınayla alındı — Hokand'ın son büyük kalesi", "toprak-kazanc", 3, 2, "dis",
   ["rusya", "hokand"], E_SAV, "Hucend", "24 Mayıs 1866 (Rus kaynağı; takvim belirtilmemiş)",
   "İrcar'da Buhara ordusunu yenen General Romanovski Hokand'a bağlı Hucend'e yöneldi; birkaç günlük bombardımandan sonra şehir merdivenlerle hücumla alındı.",
   "TDV \"rusya\" (yıl: \"Hucend (1866)\"); gün: P. L. Grossul-Tolstoy, Dela russkogo oruji i politiki v Sredney Azii (militera.lib.ru)" + OZ),
 m("1867-10-18", "Rusya Alaska'yı Sitka'da ABD'ye teslim etti — Rus Amerikası sona erdi", "toprak-kayip", 3, 3, "dis",
   ["rusya", "abd"], E_ANT, "Novoarkhangelsk (Sitka)", "18 Ekim 1867 (Gregoryen; Rus takvimiyle 6 Ekim)",
   "30 Mart 1867'de 7,2 milyon dolara satılan Alaska, Novoarhangelsk'te (Sitka) vali konağı önünde düzenlenen törenle ABD'ye teslim edildi; Rus bayrağı indirilip Amerikan bayrağı çekildi. Kodiak, Kenai, St. Michael, Nulato ve Aleut adalarındaki Rus karakolları ABD idaresine geçti.",
   "TDV \"rusya\" (satış 1867, 7.200.000 dolar); tören günü: Alaska Historical Society, \"150th Anniversary of the Alaska Treaty of Cession\" (alaskahistoricalsociety.org) ve ABD Millî Park Servisi NHL kaydı (npgallery.nps.gov)" + OZ),
 m("1869-01-01", "Krasnovodsk kuruldu — Rusya Hazar'ın doğu kıyısına çıktı", "kurulus", 2, 2, "dis",
   ["rusya", "turkmen"], ["kurulus", "genisleme", "konu-askeri"], "Krasnovodsk (Türkmenbaşı)", "1869 (kaynak yıl verir)",
   "General N. G. Stoletov'un kuvvetleri Hazar'ın doğu kıyısına çıkarak Krasnovodsk'u kurdu; Türkmen bozkırına ve Hive'ye yönelik harekâtın üssü oldu.",
   "Bolşaya Sovetskaya Entsiklopediya, \"Krasnovodsk\"" + OZ),
 m("1871-07-04", "Rusya İli (Kulca) bölgesini işgal etti", "isgal", 3, 3, "dis",
   ["rusya", "qing-hanedani"], ["isgal", "toprak", "konu-askeri"], "Almalık (Almalığ)", "22 Haziran 1871 (Jülyen) / 4 Temmuz 1871 (Gregoryen) — kaynak ikisini de verir",
   "Doğu Türkistan'daki ayaklanmalar ve Yakub Bey'in ilerleyişi gerekçesiyle General Kolpakovski İli vadisine girdi; Kulca sultanı teslim oldu. Rusya bölgeyi 'Qing düzeni yeniden kurana dek' elinde tuttu; iade 1881 St. Petersburg Antlaşması'yla kararlaştırıldı.",
   "Noda Jin, \"Reconsidering the Ili Crisis: The Ili Region under Russian Rule (1871-1881)\" (Research Institute for Humanity and Nature, chikyu.ac.jp)" + OZ),
 m("1875-05-07", "St. Petersburg Antlaşması — Sahalin'in tamamı Rusya'ya, Kuriller Japonya'ya", "antlasma", 3, 3, "dis",
   ["rusya", "meiji-japonya"], E_ANT, "Korsakov (Güney Sahalin)", "7 Mayıs 1875 (Gregoryen; Jülyen 25 Nisan)",
   "Gorçakov ile Enomoto Takeaki'nin imzaladığı antlaşmayla Japonya Sahalin'deki haklarından vazgeçti, karşılığında Rusya'ya ait Kuril adalarını aldı. 1855'ten beri ortak yönetimde olan Sahalin böylece bütünüyle Rusya'nın oldu.",
   "Rusya Cumhurbaşkanlığı Kütüphanesi, \"Treaty of 1875 between Russia and Japan on territories exchange\" (prlib.ru/en/history/619225); Encyclopaedia Britannica \"Treaty of Saint Petersburg\"; TDV \"rusya\" (1855 ortak yönetim)" + OZ),
 m("1879-01-01", "Zeya (Zeyski Sklad) aktarma deposu kuruldu — Amur altın yolları", "kurulus", 1, 1, "ic",
   "rusya", ["kurulus", "sanayi", "konu-ekonomi"], "Zeya (Zeyskiy Sklad)", "1879 (kaynak yıl verir)",
   "Zeya ırmağının yukarı altın yataklarına giden yolda aktarma deposu olarak Zeyski Sklad kuruldu.",
   "Zeya şehri idaresi resmî sayfası (admzeya.amurobl.ru)" + OZ),
 m("1892-01-01", "Onor yerleşimi kuruldu — Sahalin sürgün kolonisi", "kurulus", 1, 1, "ic",
   "rusya", ["kurulus", "surgun", "konu-idari"], "Onor", "1892 (kaynak yıl verir)",
   "Sahalin'deki sürgün (katorga) kolonileşmesi sırasında adanın içlerinde Onor yerleşimi kuruldu.",
   "Sahalin Bölge Bilimsel Kütüphanesi takvimi (calendar.libsakh.ru)" + OZ),
 m("1893-01-01", "Pamir Postu kuruldu — Rusya Pamir'e yerleşti", "kurulus", 2, 2, "dis",
   "rusya", ["kurulus", "sinir-hatti", "konu-askeri"], "Pamirski Post (Murgab)", "1893 (kaynak yıl verir); bugünkü Murgab'a taşınma 1903",
   "Afganistan ve İngiliz Hindistanı ile süren 'Büyük Oyun' sırasında Rus kuvvetleri Doğu Pamir'de Pamir Postu adlı sürekli karakolu kurdu.",
   "\"Первый российский форпост на «Крыше мира»\", CyberLeninka akademik makale (cyberleninka.ru)" + OZ),
 # ── Rusya'nın dağılışı: Baltık ─────────────────────────────────────────
 m("1918-02-16", "Litvanya Konseyi (Taryba) bağımsızlık ilan etti", "kurulus", 4, 2, "dis",
   ["litvanya"], ["kurulus", "bagimsizlik", "konu-siyasi"], "Vilnius", "16 Şubat 1918 (Gregoryen)",
   "1915'ten beri Alman işgali altındaki Litvanya'da, Alman askerî denetiminde çalışan Litvanya Konseyi Vilnius'ta bağımsızlık senedini imzaladı. Almanya Brest-Litovsk görüşmeleri sırasında bu adımı teşvik etmişti; gerçek egemenlik Kasım 1918'deki Alman çekilişine kadar gelmedi.",
   "EBSCO Research Starters, \"Baltic States Gain Independence\"; Encyclopaedia Britannica, \"Baltic states — Independence\"" + OZ),
 m("1918-02-24", "Estonya bağımsızlığını ilan etti — Bolşevik çekilişiyle Alman girişi arasında", "kurulus", 4, 2, "dis",
   ["estonya", "sovyet-rusya"], ["kurulus", "bagimsizlik", "konu-siyasi"], "Tallinn (Reval)", "24 Şubat 1918 (Gregoryen); manifesto 23 Şubat akşamı Pärnu'da okundu",
   "Bolşevik kuvvetlerin çekildiği, Alman ordusunun henüz girmediği bir günde Kurtuluş Komitesi 'Estonya Halklarına Manifesto'yu yayımladı; 23 Şubat akşamı Pärnu'da, 24 Şubat'ta Tallinn'de okundu. Ertesi gün Alman kuvvetleri Tallinn'e girdi; Almanya yeni cumhuriyeti tanımadı ve ülke (Tartu, Narva ve Pärnu dahil) Kasım 1918'e kadar Alman işgalinde kaldı.",
   "EBSCO Research Starters, \"Baltic States Gain Independence\"; Encyclopaedia Britannica, \"Baltic states — Independence\"" + OZ),
]

LEHISTAN = [
 m("1806-11-28", "Fransız ordusu Varşova'ya girdi — Prusya idaresi çöktü", "isgal", 4, 3, "dis",
   ["prusya", "fransa-cumhuriyet"], ["isgal", "toprak", "konu-askeri", "konu-siyasi"], "Varşova", "28 Kasım 1806 (Gregoryen)",
   "Jena'dan sonra doğuya ilerleyen Napolyon ordusunun öncüsü Murat, Rus generali Bennigsen'in savaşmadan çekildiği Varşova'ya girdi ve Polonyalılarca coşkuyla karşılandı. Prusya'nın 1795'te aldığı Polonya toprakları Fransız işgaline geçti; Varşova Dukalığı ancak Temmuz 1807'de Tilsit'le doğdu.",
   "Fondation Napoléon, \"The events leading up to the Battle of Eylau\" zaman çizelgesi (napoleon.org)" + OZ),
 m("1918-12-27", "Büyük Polonya (Wielkopolska) Ayaklanması Poznan'da başladı", "isyan", 5, 2, "dis",
   ["polonya", "almanya"], ["isyan", "bagimsizlik", "konu-askeri", "konu-siyasi"], "Poznan", "27 Aralık 1918 (Gregoryen)",
   "Paderewski'nin Poznan'a gelişi ve yaptığı konuşmanın ardından Polonya Askerî Örgütü üyeleri Alman garnizonuna karşı ayaklandı; Ocak 1919'un ilk iki haftasında Poznan eyaletinin büyük bölümü ayaklanmacıların eline geçti. Kazanımlar 1919 Versay Antlaşması'yla Polonya'ya bırakıldı.",
   "Polonya Cumhurbaşkanlığı resmî sitesi (president.pl), Büyük Polonya Ayaklanması anma haberi; Wielkopolska bölge portalı (regionwielkopolska.pl)" + OZ),
 m("1922-06-20", "Polonya ordusu Katowice'ye girdi — Yukarı Silezya'nın doğusu Polonya'ya geçti", "toprak-kazanc", 4, 2, "dis",
   ["polonya", "almanya"], ["toprak", "konu-siyasi"], "Kattowitz (Katowice)", "20 Haziran 1922 (Gregoryen); devir süreci 16 Temmuz 1922'de sona erdi",
   "1921 plebisiti ve Üçüncü Silezya Ayaklanması'ndan sonra Büyükelçiler Konferansı'nın çizdiği paylaşım yürürlüğe girdi; General Szeptycki komutasındaki Polonya birlikleri eski sınırı geçerek Katowice'ye girdi. Katowice Silezya voyvodalığının merkezi oldu.",
   "Polonya Tarihi portalı, \"The Third Silesian Uprising\" (polishhistory.pl)" + OZ),
]
